### ISSUE TITLE
Help!?

### ISSUE THREAD

**Issue by rodriguesfas** [EMS-TU-Ilmenau/sllurp#1]
(checkpoint) fasr@champs:~/Developer/Cronos/checkpoint$ python run_sllurp.py 
Connected to reader
1 unique tags detected
Traceback (most recent call last):
  File "run_sllurp.py", line 11, in <module>
    reader.reportTags(tags) # print the results
AttributeError: 'R420_EU' object has no attribute 'reportTags'

**Comment by beustens** [comment]
The documentation was outdated. Just use `print(tags)` to show the results. It is a list of dictionaries.
