### ISSUE TITLE
SPI Commands

### ISSUE THREAD

**Issue by smosanu** [EMS-TU-Ilmenau/sllurp#4]
Hello,

Please help me with any helpful direction on how to interface with the SPI Commands of an RFID tag. I am using an Impinj R1000 and can test with `reader.startAccess(readWords/writeWords)` the register values and Temperature sensor data of an EM4325 ([datasheet](https://www.emmicroelectronic.com/sites/default/files/products/datasheets/4325-ds_0.pdf)). However, I would like to use it in the mode "EM4325 as SPI Master and another component as SPI Slave". Fr that, I have to interface with the tag using SPI Commands that are enabled by the SendSPI Command with Command Code "E002". However, sllurp seems to have no such attribute "command code". I attempted to use the Register File Pages to write to and read from, though not successfully.

Am I missing something? Anyone knows how to switch the write/read commands to SPI commands?

Thank you!

**Comment by beustens** [comment]
sllurp implements the LLRP protocol to access the reader. The reader can access the tag via EPC Gen2 protocol over air. SPI is not an air protocol and completely unrelated to this project, you have to connect a microcontroller to the RFID chip itself on its SPI interface (pins 3, 4, 5, 6) and implement the communication.
